words_fr = [
{text: "14-Juillet",category:""},
{text: "1er-Avril",category:""},
{text: "Abeille",category:""},
{text: "Abricot",category:""},
{text: "Acrobate",category:""},
{text: "Acteur",category:""},
{text: "Aéroport",category:""},
{text: "Agneau",category:""},
{text: "Agriculteur",category:""},
{text: "Aigle",category:""},
{text: "Aiguille",category:""},
{text: "Ail",category:""},
{text: "Aile",category:""},
{text: "Air",category:""},
{text: "Albert Einstein",category:""},
{text: "Alice au pays des merveilles",category:""},
{text: "Allumette",category:""},
{text: "Amazone",category:""},
{text: "Ambulance",category:""},
{text: "Ampoule",category:""},
{text: "Ananas",category:""},
{text: "Âne",category:""},
{text: "Animal",category:""},
{text: "Anniversaire",category:""},
{text: "Anubis",category:""},
{text: "Aphrodite",category:""},
{text: "Apiculteur",category:""},
{text: "Apollon",category:""},
{text: "Appareil dentaire",category:""},
{text: "Appareil photographique",category:""},
{text: "Aquarium",category:""},
{text: "Araignée",category:""},
{text: "Arbre",category:""},
{text: "Arc-en-ciel",category:""},
{text: "Archéologue",category:""},
{text: "Architecte",category:""},
{text: "Arès",category:""},
{text: "Arête",category:""},
{text: "Argent",category:""},
{text: "Arrosoir",category:""},
{text: "Artémis",category:""},
{text: "Ascenseur",category:""},
{text: "Asperge",category:""},
{text: "Aspirateur",category:""},
{text: "Aspirine",category:""},
{text: "Assiette",category:""},
{text: "Astérix",category:""},
{text: "Astronaute",category:""},
{text: "Astronomie",category:""},
{text: "Athéna",category:""},
{text: "Atterrir",category:""},
{text: "Au clair de la lune",category:""},
{text: "Aubergine",category:""},
{text: "Automne",category:""},
{text: "Autruche",category:""},
{text: "Avion",category:""},
{text: "Bague",category:""},
{text: "Baguette",category:""},
{text: "Bâiller",category:""},
{text: "Balai",category:""},
{text: "Balançoire",category:""},
{text: "Baleine",category:""},
{text: "Baleine bleue",category:""},
{text: "Balle",category:""},
{text: "Ballon",category:""},
{text: "Banane",category:""},
{text: "Banc",category:""},
{text: "Bande dessinée",category:""},
{text: "Barbe",category:""},
{text: "Barque",category:""},
{text: "Barrette",category:""},
{text: "Basket-ball",category:""},
{text: "Bateau",category:""},
{text: "Bâton",category:""},
{text: "Bavoir",category:""},
{text: "Bec",category:""},
{text: "Béquille",category:""},
{text: "Berger",category:""},
{text: "Berger allemand",category:""},
{text: "Bermuda",category:""},
{text: "Beurre",category:""},
{text: "Biberon",category:""},
{text: "Bibliothèque",category:""},
{text: "Bifteck",category:""},
{text: "Big Ben",category:""},
{text: "Bijou",category:""},
{text: "Bijoutier",category:""},
{text: "Bille",category:""},
{text: "Billet",category:""},
{text: "Biologie",category:""},
{text: "Biscuit",category:""},
{text: "Bison",category:""},
{text: "Blé",category:""},
{text: "Bœuf",category:""},
{text: "Boisson",category:""},
{text: "Bol",category:""},
{text: "Bonbon",category:""},
{text: "Bonnet",category:""},
{text: "Boomerang",category:""},
{text: "Botte",category:""},
{text: "Bouche",category:""},
{text: "Boucher",category:""},
{text: "Boucherie",category:""},
{text: "Bouchon",category:""},
{text: "Boue",category:""},
{text: "Bouée",category:""},
{text: "Boulanger",category:""},
{text: "Boulangerie",category:""},
{text: "Bouteille",category:""},
{text: "Bouton",category:""},
{text: "Bracelet",category:""},
{text: "Bras",category:""},
{text: "Bretelle",category:""},
{text: "Brocoli",category:""},
{text: "Brosse à dents",category:""},
{text: "Brouette",category:""},
{text: "Bugs Bunny",category:""},
{text: "Bureau",category:""},
{text: "Bus",category:""},
{text: "Cabane",category:""},
{text: "Cadeau",category:""},
{text: "Cadenas",category:""},
{text: "Café",category:""},
{text: "Cafetière",category:""},
{text: "Cage",category:""},
{text: "Cagoule",category:""},
{text: "Caillou",category:""},
{text: "Calculette",category:""},
{text: "Calendrier",category:""},
{text: "Caméléon",category:""},
{text: "Caméra",category:""},
{text: "Camion",category:""},
{text: "Camping-car",category:""},
{text: "Canapé",category:""},
{text: "Canard",category:""},
{text: "Caniche",category:""},
{text: "Canne à pêche",category:""},
{text: "Car",category:""},
{text: "Caravane",category:""},
{text: "Carnaval",category:""},
{text: "Carotte",category:""},
{text: "Cartable",category:""},
{text: "Casque",category:""},
{text: "Casquette",category:""},
{text: "Casserole",category:""},
{text: "Castor",category:""},
{text: "Ceinture",category:""},
{text: "Cendrillon",category:""},
{text: "Centaure",category:""},
{text: "Cerbère",category:""},
{text: "Cerceau",category:""},
{text: "Céréale",category:""},
{text: "Cerf",category:""},
{text: "Cerf-volant",category:""},
{text: "Cerise",category:""},
{text: "Cerveau",category:""},
{text: "Chaise",category:""},
{text: "Chameau",category:""},
{text: "Champignon",category:""},
{text: "Chandeleur",category:""},
{text: "Chanter",category:""},
{text: "Chanteur",category:""},
{text: "Chapeau",category:""},
{text: "Chariot",category:""},
{text: "Charlemagne",category:""},
{text: "Charpentier",category:""},
{text: "Chasseur",category:""},
{text: "Chat",category:""},
{text: "Châtaigne",category:""},
{text: "Château",category:""},
{text: "Chaton",category:""},
{text: "Chaussette",category:""},
{text: "Chaussettes",category:""},
{text: "Chausson",category:""},
{text: "Chaussure",category:""},
{text: "Chauve-souris",category:""},
{text: "Chemise",category:""},
{text: "Chenille",category:""},
{text: "Chercheur d'or",category:''},
{text: "Cheval",category:""},
{text: "Cheval de Troie",category:""},
{text: "Chevaliers de la Table ronde",category:""},
{text: "Cheveu",category:""},
{text: "Cheville",category:""},
{text: "Chèvre",category:""},
{text: "Chien",category:""},
{text: "Chiffon",category:""},
{text: "Chiot",category:""},
{text: "Chips",category:""},
{text: "Chirurgien",category:""},
{text: "Chocolat",category:""},
{text: "Chou",category:""},
{text: "Chouette",category:""},
{text: "Christophe Colomb",category:""},
{text: "Chuchoter",category:""},
{text: "Cigogne",category:""},
{text: "Cil",category:""},
{text: "Ciseaux",category:""},
{text: "Citron",category:""},
{text: "Citrouille",category:""},
{text: "Clé",category:""},
{text: "Clémentine",category:""},
{text: "Cléopâtre",category:""},
{text: "Clignotant",category:""},
{text: "Clou",category:""},
{text: "Clown",category:""},
{text: "Coccinelle",category:""},
{text: "Cochon",category:""},
{text: "Cocotte",category:""},
{text: "Cœur",category:""},
{text: "Coffre",category:""},
{text: "Coiffeur",category:""},
{text: "Collant",category:""},
{text: "Colle",category:""},
{text: "Collier",category:""},
{text: "Colorier",category:""},
{text: "Concombre",category:""},
{text: "Conduire",category:""},
{text: "Confiture",category:""},
{text: "Console de jeu",category:""},
{text: "Coq",category:""},
{text: "Coquelicot",category:""},
{text: "Coquillage",category:""},
{text: "Corbeau",category:""},
{text: "Corbeille",category:""},
{text: "Corde",category:""},
{text: "Cou",category:""},
{text: "Coude",category:""},
{text: "Coudre",category:""},
{text: "Couette",category:""},
{text: "Couronne",category:""},
{text: "Coussin",category:""},
{text: "Couteau",category:""},
{text: "Couver",category:""},
{text: "Couvercle",category:""},
{text: "Couverture",category:""},
{text: "Cow-boy",category:""},
{text: "Crabe",category:""},
{text: "Cracher",category:""},
{text: "Craie",category:""},
{text: "Crapaud",category:""},
{text: "Cravate",category:""},
{text: "Crayon",category:""},
{text: "Crèche",category:""},
{text: "Crème solaire",category:""},
{text: "Crêpe",category:""},
{text: "Creuser",category:""},
{text: "Crevette",category:""},
{text: "Crochet",category:""},
{text: "Crocodile",category:""},
{text: "Croissant",category:""},
{text: "Cronos",category:""},
{text: "Croûte",category:""},
{text: "Cube",category:""},
{text: "Cuillère",category:""},
{text: "Cuisinier",category:""},
{text: "Cuisse",category:""},
{text: "Culotte",category:""},
{text: "Cyclisme",category:""},
{text: "Cyclope",category:""},
{text: "Cygne",category:""},
{text: "Danser",category:""},
{text: "Dauphin",category:""},
{text: "Dé",category:""},
{text: "Déchirer",category:""},
{text: "Déguisement",category:""},
{text: "Dent",category:""},
{text: "Dentifrice",category:""},
{text: "Dentiste",category:""},
{text: "Dessert",category:""},
{text: "Diamant",category:""},
{text: "Diane",category:""},
{text: "Dictionnaire",category:""},
{text: "Dindon",category:""},
{text: "Dînette",category:""},
{text: "Dinosaure",category:""},
{text: "Dionysos",category:""},
{text: "Doigt",category:""},
{text: "Domino",category:""},
{text: "Dompteur",category:""},
{text: "Donald Duck",category:""},
{text: "Dormir",category:""},
{text: "Dos",category:""},
{text: "Dragon",category:""},
{text: "Drap",category:""},
{text: "Dromadaire",category:""},
{text: "Eau",category:""},
{text: "Écharpe",category:""},
{text: "Échasse",category:""},
{text: "Échecs",category:""},
{text: "Échelle",category:""},
{text: "École",category:""},
{text: "École maternelle",category:""},
{text: "Écran",category:""},
{text: "Écrire",category:""},
{text: "Écureuil",category:""},
{text: "Égypte",category:""},
{text: "Élastique",category:""},
{text: "Éléphant",category:""},
{text: "Elfe",category:""},
{text: "Empire State Building",category:""},
{text: "Endive",category:""},
{text: "Entonnoir",category:""},
{text: "Enveloppe",category:""},
{text: "Épaule",category:""},
{text: "Épingle",category:""},
{text: "Épiphanie",category:""},
{text: "Éponge",category:""},
{text: "Escalier mécanique",category:""},
{text: "Escargot",category:""},
{text: "Escrime",category:""},
{text: "Espagne",category:""},
{text: "Essence",category:""},
{text: "États-Unis",category:""},
{text: "Été",category:""},
{text: "Étoile",category:""},
{text: "Étoile de mer",category:""},
{text: "Étoile filante",category:""},
{text: "Everest",category:""},
{text: "Facteur",category:""},
{text: "Fantôme",category:""},
{text: "Farine",category:""},
{text: "Fauteuil",category:""},
{text: "Fauteuil roulant",category:""},
{text: "Fée",category:""},
{text: "Fer à repasser",category:""},
{text: "Ferme",category:""},
{text: "Fesse",category:""},
{text: "Fête de la musique",category:""},
{text: "Fête des grands-mères",category:""},
{text: "Fête des mères",category:""},
{text: "Fête des pères",category:""},
{text: "Feutre",category:""},
{text: "Fève",category:""},
{text: "Ficelle",category:""},
{text: "Fièvre",category:""},
{text: "Fil",category:""},
{text: "Fille",category:""},
{text: "Flamant rose",category:""},
{text: "Fleur",category:""},
{text: "Fleuriste",category:""},
{text: "Flûte traversière",category:""},
{text: "Football",category:""},
{text: "Forgeron",category:""},
{text: "Fossile",category:""},
{text: "Four",category:""},
{text: "Fourchette",category:""},
{text: "Fourmi",category:""},
{text: "Fraise",category:""},
{text: "Framboise",category:""},
{text: "France",category:""},
{text: "Frein",category:""},
{text: "Frisbee",category:""},
{text: "Frites",category:""},
{text: "Fromage",category:""},
{text: "Front",category:""},
{text: "Fruit",category:""},
{text: "Fusée",category:""},
{text: "Fusée spatiale",category:""},
{text: "Gaïa",category:""},
{text: "Galère",category:""},
{text: "Galette",category:""},
{text: "Gandhi",category:""},
{text: "Gant",category:""},
{text: "Garage",category:""},
{text: "Garçon",category:""},
{text: "Gardien",category:""},
{text: "Gare",category:""},
{text: "Gargamel",category:""},
{text: "Gâteau",category:""},
{text: "Gaulois",category:""},
{text: "Géant",category:""},
{text: "Genou",category:""},
{text: "Géologie",category:""},
{text: "Girafe",category:""},
{text: "Glaçon",category:""},
{text: "Gobelet",category:""},
{text: "Golf",category:""},
{text: "Gomme",category:""},
{text: "Gorille",category:""},
{text: "Grande Muraille de Chine",category:""},
{text: "Grèce",category:""},
{text: "Grenouille",category:""},
{text: "Griffe",category:""},
{text: "Groseille",category:""},
{text: "Grotte",category:""},
{text: "Grue",category:""},
{text: "Gruyère",category:""},
{text: "Guépard",category:""},
{text: "Guêpe",category:""},
{text: "Guirlande",category:""},
{text: "Gymnase",category:""},
{text: "Gymnastique",category:""},
{text: "Hadès",category:""},
{text: "Halloween",category:""},
{text: "Hamster",category:""},
{text: "Handball",category:""},
{text: "Haricot vert",category:""},
{text: "Hélicoptère",category:""},
{text: "Héphaïstos",category:""},
{text: "Héra",category:""},
{text: "Héraclès",category:""},
{text: "Herbe",category:""},
{text: "Hérisson",category:""},
{text: "Hermès",category:""},
{text: "Hibou",category:""},
{text: "Hippocampe",category:""},
{text: "Hippopotame",category:""},
{text: "Hirondelle",category:""},
{text: "Hiver",category:""},
{text: "Hockey sur glace",category:""},
{text: "Hôpital",category:""},
{text: "Hoquet",category:""},
{text: "Horloge",category:""},
{text: "Horus",category:""},
{text: "Hôtel",category:""},
{text: "Huile",category:""},
{text: "Husky",category:""},
{text: "Icare",category:""},
{text: "Idéfix",category:""},
{text: "Imprimante",category:""},
{text: "Infirmier",category:""},
{text: "Informaticien",category:""},
{text: "Insecte",category:""},
{text: "Italie",category:""},
{text: "Jambe",category:""},
{text: "Jambon",category:""},
{text: "Janus",category:""},
{text: "Japon",category:""},
{text: "Jeanne d'Arc",category:''},
{text: "Jolly Jumper",category:""},
{text: "Jongler",category:""},
{text: "Jongleur",category:""},
{text: "Joue",category:""},
{text: "Journaliste",category:""},
{text: "Judo",category:""},
{text: "Jumelles",category:""},
{text: "Jument",category:""},
{text: "Jupe",category:""},
{text: "Jus d'orange",category:''},
{text: "Kangourou",category:""},
{text: "Karaté",category:""},
{text: "Ketchup",category:""},
{text: "Kilt",category:""},
{text: "Kiwi",category:""},
{text: "La Reine des neiges",category:""},
{text: "La Schtroumpfette",category:""},
{text: "Lacet",category:""},
{text: "Lait",category:""},
{text: "Lancer du disque",category:""},
{text: "Langue",category:""},
{text: "Lapin",category:""},
{text: "Larme",category:""},
{text: "Las Vegas",category:""},
{text: "Lave-linge",category:""},
{text: "Le Capitaine Haddock",category:""},
{text: "Le Grand Schtroumpf",category:""},
{text: "Le Marsupilami",category:""},
{text: "Le Monde de Nemo",category:""},
{text: "Le Petit Prince",category:""},
{text: "Le Roi lion",category:""},
{text: "Léopard",category:""},
{text: "Les Schtroumpfs",category:""},
{text: "Lèvre",category:""},
{text: "Lèvres",category:""},
{text: "Lézard",category:""},
{text: "Libellule",category:""},
{text: "Libraire",category:""},
{text: "Licorne",category:""},
{text: "Lièvre",category:""},
{text: "Limace",category:""},
{text: "Lion",category:""},
{text: "Lire",category:""},
{text: "Lit",category:""},
{text: "Livre",category:""},
{text: "Louche",category:""},
{text: "Loup",category:""},
{text: "Loupe",category:""},
{text: "Loup-Garou",category:""},
{text: "Lucky Luke",category:""},
{text: "Luge",category:""},
{text: "Lune",category:""},
{text: "Lunettes",category:""},
{text: "Lunettes de soleil",category:""},
{text: "Lutin",category:""},
{text: "Maçon",category:""},
{text: "Magicien",category:""},
{text: "Maillot",category:""},
{text: "Maillot de bain",category:""},
{text: "Main",category:""},
{text: "Maison",category:""},
{text: "Manège",category:""},
{text: "Mante religieuse",category:""},
{text: "Manteau",category:""},
{text: "Marguerite",category:""},
{text: "Marie Curie",category:""},
{text: "Marin",category:""},
{text: "Marionnette",category:""},
{text: "Marmotte",category:""},
{text: "Marteau",category:""},
{text: "Médecin",category:""},
{text: "Médecine",category:""},
{text: "Médicament",category:""},
{text: "Méduse",category:""},
{text: "Melon",category:""},
{text: "Menton",category:""},
{text: "Merlin l'Enchanteur",category:""},
{text: "Métal",category:""},
{text: "Météorite",category:""},
{text: "Métro",category:""},
{text: "Mexique",category:""},
{text: "Mickey Mouse",category:""},
{text: "Microscope",category:""},
{text: "Mie",category:""},
{text: "Miel",category:""},
{text: "Mille-pattes",category:""},
{text: "Milou",category:""},
{text: "Minnie Mouse",category:""},
{text: "Minotaure",category:""},
{text: "Miroir",category:""},
{text: "Moineau",category:""},
{text: "Monstre du Loch Ness",category:""},
{text: "Mont Blanc",category:""},
{text: "Montagne",category:""},
{text: "Montgolfière",category:""},
{text: "Montre",category:""},
{text: "Morse (animal)",category:""},
{text: "Moteur",category:""},
{text: "Moto",category:""},
{text: "Mouche",category:""},
{text: "Mouchoir",category:""},
{text: "Mouette",category:""},
{text: "Moufle",category:""},
{text: "Moule",category:""},
{text: "Moulin",category:""},
{text: "Moustache",category:""},
{text: "Moustique",category:""},
{text: "Moutarde",category:""},
{text: "Mouton",category:""},
{text: "Mûre",category:""},
{text: "Musique",category:""},
{text: "Nager",category:""},
{text: "Nain",category:""},
{text: "Nappe",category:""},
{text: "Nasique",category:""},
{text: "Navet",category:""},
{text: "Neil Armstrong",category:""},
{text: "Nez",category:""},
{text: "Nid",category:""},
{text: "Nil",category:""},
{text: "Noël",category:""},
{text: "Noisette",category:""},
{text: "Noix",category:""},
{text: "Nombril",category:""},
{text: "Nouvel An Chinois",category:""},
{text: "Noyau",category:""},
{text: "Obélix",category:""},
{text: "Odin",category:""},
{text: "Œil",category:""},
{text: "Œuf",category:""},
{text: "Ogre",category:""},
{text: "Oie",category:""},
{text: "Oignon",category:""},
{text: "Oiseau",category:""},
{text: "Olive",category:""},
{text: "Ongle",category:""},
{text: "ONU (Organisation des Nations unies)",category:""},
{text: "Opticien",category:""},
{text: "Or",category:""},
{text: "Orange",category:""},
{text: "Ordinateur",category:""},
{text: "Ordonnance",category:""},
{text: "Oreille",category:""},
{text: "Oreiller",category:""},
{text: "Ornithorynque",category:""},
{text: "Orque",category:""},
{text: "Orteil",category:""},
{text: "Os",category:""},
{text: "Otarie",category:""},
{text: "Ours",category:""},
{text: "Ours blanc",category:""},
{text: "Oursin",category:""},
{text: "Ouvre-boîte",category:""},
{text: "Ouvrier",category:""},
{text: "Paille",category:""},
{text: "Pain",category:""},
{text: "Palais",category:""},
{text: "Pamplemousse",category:""},
{text: "Panda",category:""},
{text: "Pansement",category:""},
{text: "Pantalon",category:""},
{text: "Panthère",category:""},
{text: "Papier alu",category:""},
{text: "Papillon",category:""},
{text: "Parapluie",category:""},
{text: "Parasol",category:""},
{text: "Paris",category:""},
{text: "Pâte",category:""},
{text: "Pâte à modeler",category:""},
{text: "Pâtes",category:""},
{text: "Pâtisserie",category:""},
{text: "Patte",category:""},
{text: "Peau",category:""},
{text: "Pêche",category:""},
{text: "Pêcheur",category:""},
{text: "Pédale",category:""},
{text: "Pégase",category:""},
{text: "Peigne",category:""},
{text: "Pélican",category:""},
{text: "Pelle",category:""},
{text: "Peluche",category:""},
{text: "Perceuse",category:""},
{text: "Perle",category:""},
{text: "Perroquet",category:""},
{text: "Persil",category:""},
{text: "Pétanque",category:""},
{text: "Petit pois",category:""},
{text: "Pharmacie",category:""},
{text: "Phénix",category:""},
{text: "Phoque",category:""},
{text: "Piano",category:""},
{text: "Picsou",category:""},
{text: "Pied",category:""},
{text: "Pieuvre",category:""},
{text: "Pigeon",category:""},
{text: "Pinceau",category:""},
{text: "Pinocchio",category:""},
{text: "Pion",category:""},
{text: "Piquer",category:""},
{text: "Piqûre",category:""},
{text: "Pizza",category:""},
{text: "Planche",category:""},
{text: "Planche à découper",category:""},
{text: "Plastique",category:""},
{text: "Plâtre",category:""},
{text: "Pleurer",category:""},
{text: "Plombier",category:""},
{text: "Plume",category:""},
{text: "Pneu",category:""},
{text: "Poêle",category:""},
{text: "Poignet",category:""},
{text: "Poing",category:""},
{text: "Poire",category:""},
{text: "Poireau",category:""},
{text: "Poison",category:""},
{text: "Poisson",category:""},
{text: "Police",category:""},
{text: "Pomme",category:""},
{text: "Pomme de terre",category:""},
{text: "Pompier",category:""},
{text: "Poney",category:""},
{text: "Pont",category:""},
{text: "Popcorn",category:""},
{text: "Port",category:""},
{text: "Porte",category:""},
{text: "Portemanteau",category:""},
{text: "Poséidon",category:""},
{text: "Poubelle",category:""},
{text: "Pouce",category:""},
{text: "Poulain",category:""},
{text: "Poule",category:""},
{text: "Poulet",category:""},
{text: "Poumon",category:""},
{text: "Poupée",category:""},
{text: "Poussette",category:""},
{text: "Poussin",category:""},
{text: "Prince",category:""},
{text: "Princesse",category:""},
{text: "Printemps",category:""},
{text: "Prométhée",category:""},
{text: "Prune",category:""},
{text: "Puissance 4",category:""},
{text: "Pull-over",category:""},
{text: "Purée",category:""},
{text: "Putois",category:""},
{text: "Puzzle",category:""},
{text: "Pyjama",category:""},
{text: "Pyramides d'Égypte",category:""},
{text: "Quetzalcoatl",category:""},
{text: "Queue",category:""},
{text: "Raclette",category:""},
{text: "Radiateur",category:""},
{text: "Radio",category:""},
{text: "Radis",category:""},
{text: "Raisin",category:""},
{text: "Rantanplan",category:""},
{text: "Raquette",category:""},
{text: "Rasoir",category:""},
{text: "Rat",category:""},
{text: "Râteau",category:""},
{text: "Raton laveur",category:""},
{text: "Rê",category:""},
{text: "Recette",category:""},
{text: "Réfrigérateur",category:""},
{text: "Reine",category:""},
{text: "Renard",category:""},
{text: "Requin",category:""},
{text: "Restaurant",category:""},
{text: "Réveil",category:""},
{text: "Rêver",category:""},
{text: "Rhinocéros",category:""},
{text: "Rideau",category:""},
{text: "Riz",category:""},
{text: "Robe",category:""},
{text: "Robinet",category:""},
{text: "Robinson Crusoé",category:""},
{text: "Robot",category:""},
{text: "Roi",category:""},
{text: "Roi Arthur",category:""},
{text: "Rome",category:""},
{text: "Roue",category:""},
{text: "Rouge-Gorge",category:""},
{text: "Rouleau à pâtisserie",category:""},
{text: "Sable",category:""},
{text: "Saint-Valentin",category:""},
{text: "Salade",category:""},
{text: "Salade de fruits",category:""},
{text: "Saladier",category:""},
{text: "Salière",category:""},
{text: "Sang",category:""},
{text: "Sanglier",category:""},
{text: "Sapin",category:""},
{text: "Sardine",category:""},
{text: "S'asseoir",category:""},
{text: "Satyre",category:""},
{text: "Saumon",category:""},
{text: "Saut à la perche",category:""},
{text: "Savon",category:""},
{text: "Scie",category:""},
{text: "Science",category:""},
{text: "Scooter",category:""},
{text: "Scorpion",category:""},
{text: "Se baisser",category:""},
{text: "Se coucher",category:""},
{text: "Se déshabiller",category:""},
{text: "Se laver",category:""},
{text: "Se maquiller",category:""},
{text: "Se moucher",category:""},
{text: "Seau",category:""},
{text: "Sein",category:""},
{text: "Sel",category:""},
{text: "Serpent",category:""},
{text: "Serpent de mer",category:""},
{text: "Serrure",category:""},
{text: "Serviette",category:""},
{text: "Shampooing",category:""},
{text: "Sherlock Holmes",category:""},
{text: "Shiva",category:""},
{text: "Singe",category:""},
{text: "Sirène",category:""},
{text: "Ski",category:""},
{text: "Soleil",category:""},
{text: "Sonnette",category:""},
{text: "Sorcière",category:""},
{text: "Soucoupe volante",category:""},
{text: "Soupe",category:""},
{text: "Sourcil",category:""},
{text: "Souris",category:""},
{text: "Sous-marin",category:""},
{text: "Sphinx",category:""},
{text: "Squelette",category:""},
{text: "Statue de la Liberté",category:""},
{text: "Stéthoscope",category:""},
{text: "Stylo",category:""},
{text: "Sucre",category:""},
{text: "Superman",category:""},
{text: "Table",category:""},
{text: "Tableau",category:""},
{text: "Tablette",category:""},
{text: "Tablier",category:""},
{text: "Taille-crayon",category:""},
{text: "Talon",category:""},
{text: "Tambour",category:""},
{text: "Tandem",category:""},
{text: "Tapis",category:""},
{text: "Tapis volant",category:""},
{text: "Tarte",category:""},
{text: "Tartine",category:""},
{text: "Tasse",category:""},
{text: "Taupe",category:""},
{text: "Taureau",category:""},
{text: "Télécommande",category:""},
{text: "Téléphone",category:""},
{text: "Téléphone portable",category:""},
{text: "Télévision",category:""},
{text: "Tennis",category:""},
{text: "Tente",category:""},
{text: "Tête",category:""},
{text: "Téter",category:""},
{text: "Thé",category:""},
{text: "Thermomètre",category:""},
{text: "Thor",category:""},
{text: "Thot",category:""},
{text: "Tigre",category:""},
{text: "Timbre",category:""},
{text: "Tiroir",category:""},
{text: "Toboggan",category:""},
{text: "Tomate",category:""},
{text: "Torchon",category:""},
{text: "Tortue",category:""},
{text: "Tour de Pise",category:""},
{text: "Tour Eiffel",category:""},
{text: "Tournevis",category:""},
{text: "Toutatis",category:""},
{text: "Tracteur",category:""},
{text: "Train",category:""},
{text: "Traîneau",category:""},
{text: "Trampoline",category:""},
{text: "Trésor",category:""},
{text: "Tricycle",category:""},
{text: "Trompette",category:""},
{text: "Trône",category:""},
{text: "Trottinette",category:""},
{text: "Trou noir",category:""},
{text: "Trousse",category:""},
{text: "Truie",category:""},
{text: "Tuyau",category:""},
{text: "UE (Union européenne)",category:""},
{text: "Ulysse",category:""},
{text: "Un Saint-Bernard",category:""},
{text: "Un, deux, trois, soleil",category:""},
{text: "Une Laisse",category:""},
{text: "Une souris verte",category:""},
{text: "Univers",category:""},
{text: "Urine",category:""},
{text: "Usine",category:""},
{text: "Vache",category:""},
{text: "Valise",category:""},
{text: "Valkyrie",category:""},
{text: "Vampire",category:""},
{text: "Vase",category:""},
{text: "Vautour",category:""},
{text: "Veau",category:""},
{text: "Vélo",category:""},
{text: "Venise",category:""},
{text: "Ventre",category:""},
{text: "Ver de terre",category:""},
{text: "Verre",category:""},
{text: "Vétérinaire",category:""},
{text: "Viande",category:""},
{text: "Vikings",category:""},
{text: "Vin",category:""},
{text: "Vis",category:""},
{text: "Visage",category:""},
{text: "Voile",category:""},
{text: "Voiture",category:""},
{text: "Volcan",category:""},
{text: "Volet",category:""},
{text: "Xylophone",category:""},
{text: "Yahourt",category:""},
{text: "Yangzi Jiang",category:""},
{text: "Yéti",category:""},
{text: "Zèbre",category:""},
{text: "Zeus",category:""},
{text: "Zombie",category:""},
{text: "Zoo",category:""},
]