words_es = [
    {text:'cumpleaños',category:'evento'},
    {text:'elecciones',category:'evento'},
    {text:'festivo',category:'festividad'},
    {text:'hanukkah',category:'festividad'},
    {text:'venta de garaje',category:'evento'},
    {text:'funeral',category:'evento'},
    {text:'abuela',category:'familia'},
    {text:'abuelo',category:'familia'},
    {text:'esposo',category:'familia'},
    {text:'kwanzaa',category:'festividad'},
    {text:'padres',category:'familia'},
    {text:'boda',category:'festividad'},
    {text:'pulsera',category:'objetos de valor'},
    {text:'cristal',category:'objetos de valor'},
    {text:'diamante',category:'objetos de valor'},
    {text:'esmeralda',category:'objetos de valor'},
    {text:'joyas',category:'objetos de valor'},
    {text:'bromance',category:'social'},
    {text:'damas',category:'juegos'},
    {text:'seguidor',category:'social'},
    {text:'choca esos 5',category:'social'},
    {text:'hula hoop',category:'juguete'},
    {text:'joystick',category:'juegos'},
    {text:'limonada',category:'bebida'},
    {text:'matrimonio',category:'social'},
    {text:'monopoly',category:'juegos'},
    {text:'molinete',category:'juguete'},
    {text:'scrabble',category:'juegos'},
    {text:'batido',category:'bebida'},
    {text:'columpio',category:'juguete'},
    {text:'globo',category:'juguete'},
    {text:'divorcio',category:'social'},
    {text:'dreidel',category:'juguete'},
    {text:'amienemigo',category:'social'},
    {text:'gameboy',category:'juguete'},
    {text:'martini',category:'bebida'},
    {text:'pinball',category:'juegos'},
    {text:'sixpack',category:'bebida'},
    {text:'tequila',category:'bebida'},
    {text:'whiskey',category:'bebida'},
    {text:'yahtzee',category:'juegos'},
    {text:'taburete',category:'muebles'},
    {text:'estante',category:'muebles'},
    {text:'motosierra',category:'herramienta'},
    {text:'tijeras',category:'herramienta'},
    {text:'pinzas',category:'herramienta'},
    {text:'cama de agua',category:'muebles'},
    {text:'bañera',category:'muebles'},
    {text:'litera',category:'muebles'},
    {text:'gabinete',category:'muebles'},
    {text:'brújula',category:'herramienta'},
    {text:'pata de cabra',category:'herramienta'},
    {text:'cómoda',category:'muebles'},
    {text:'recogedor',category:'herramienta'},
    {text:'grapadora',category:'herramienta'},
    {text:'pintalabios',category:'artículos de tocador'},
    {text:'perfume',category:'artículos de aseo'},
    {text:'champú',category:'artículos de aseo'},
    {text:'lima de uñas',category:'artículos de aseo'},
    {text:'crema solar',category:'artículos de aseo'},
    {text:'tinte para el cabello',category:'artículos de aseo'},
    {text:'gel para el cabello',category:'artículos de aseo'},
    {text:'máscara',category:'artículos de aseo'},
    {text:'ordenador',category:'informática'},
    {text:'facebook',category:'informática'},
    {text:'cortafuegos',category:'informática'},
    {text:'teclado',category:'informática'},
    {text:'contraseña',category:'informática'},
    {text:'hashtag',category:'informática'},
    {text:'macbook',category:'informática'},
    {text:'twitter',category:'informática'},
    {text:'catapulta',category:'arma'},
    {text:'ballesta',category:'arma'},
    {text:'dinamita',category:'arma'},
    {text:'bola de fuego',category:'arma'},
    {text:'bayoneta',category:'arma'},
    {text:'bazuca',category:'arma'},
    {text:'pistola',category:'arma'},
    {text:'misil',category:'arma'},
    {text:'escopeta',category:'arma'},
    {text:'torpedo',category:'arma'},
    {text:'cañón',category:'arma'},
    {text:'orejeras',category:'ropa'},
    {text:'parche en el ojo',category:'accesorio'},
    {text:'cinta para la cabeza',category:'accesorio'},
    {text:'rodilleras',category:'accesorio'},
    {text:'collar',category:'accesorio'},
    {text:'nosering',category:'accesorio'},
    {text:'peto',category:'ropa'},
    {text:'pantsuit',category:'ropa'},
    {text:'sombrero de fiesta',category:'accesorio'},
    {text:'impermeable',category:'ropa'},
    {text:'cordón de zapato',category:'accesorio'},
    {text:'zapatillas',category:'ropa'},
    {text:'tenis',category:'ropa'},
    {text:'traje de baño',category:'ropa'},
    {text:'paraguas',category:'accesorio'},
    {text:'pañuelo en la cabeza',category:'accesorio'},
    {text:'pendiente',category:'accesorio'},
    {text:'goma del pelo',category:'accesorio'},
    {text:'bolsa de mano',category:'accesorio'},
    {text:'guantes',category:'ropa'},
    {text:'pijama',category:'ropa'},
    {text:'sandalias',category:'ropa'},
    {text:'suéter',category:'ropa'},
    {text:'bikini',category:'ropa'},
    {text:'muletas',category:'medicina'},
    {text:'caspa',category:'medicina'},
    {text:'dentaduras postizas',category:'medicina'},
    {text:'primeros auxilios',category:'medicina'},
    {text:'dolor de cabeza',category:'medicina'},
    {text:'hospital',category:'medicina'},
    {text:'insomnio',category:'medicina'},
    {text:'medicamento',category:'medicina'},
    {text:'corte de papel',category:'medicina'},
    {text:'mareado',category:'medicina'},
    {text:'quemadura de sol',category:'medicina'},
    {text:'vacuna',category:'medicina'},
    {text:'vitamina',category:'medicina'},
    {text:'ramas',category:'planta'},
    {text:'berenjena',category:'planta'},
    {text:'hongkong',category:'geografía'},
    {text:'palmera',category:'planta'},
    {text:'piñón',category:'planta'},
    {text:'pino',category:'planta'},
    {text:'primavera',category:'planta'},
    {text:'escocia',category:'geografía'},
    {text:'américa',category:'geografía'},
    {text:'atlanta',category:'geografía'},
    {text:'bahamas',category:'geografía'},
    {text:'inglaterra',category:'geografía'},
    {text:'finlandia',category:'geografía'},
    {text:'florida',category:'geografía'},
    {text:'alemania',category:'geografía'},
    {text:'holanda',category:'geografía'},
    {text:'irlanda',category:'geografía'},
    {text:'jamaica',category:'geografía'},
    {text:'nueva york',category:'geografía'},
    {text:'roble',category:'planta'},
    {text:'orlando',category:'geografía'},
    {text:'algas marinas',category:'planta'},
    {text:'bambú',category:'planta'},
    {text:'zanahoria',category:'planta'},
    {text:'apio',category:'planta'},
    {text:'cereza',category:'planta'},
    {text:'ajo',category:'planta'},
    {text:'uvas',category:'planta'},
    {text:'columna vertebral',category:'anatomía'},
    {text:'cementerio',category:'ubicación'},
    {text:'frente',category:'anatomía'},
    {text:'bigote',category:'anatomía'},
    {text:'vello nasal',category:'anatomía'},
    {text:'hombro',category:'anatomía'},
    {text:'esqueleto',category:'anatomía'},
    {text:'tentáculo',category:'anatomía'},
    {text:'bigotes',category:'anatomía'},
    {text:'ojo',category:'anatomía'},
    {text:'ceja',category:'anatomía'},
    {text:'pestaña',category:'anatomía'},
    {text:'rótula',category:'anatomía'},
    {text:'nudillo',category:'anatomía'},
    {text:'biblioteca',category:'ubicación'},
    {text:'mansión',category:'ubicación'},
    {text:'tienda de mascotas',category:'ubicación'},
    {text:'estómago',category:'anatomía'},
    {text:'teatro',category:'ubicación'},
    {text:'unicejo',category:'anatomía'},
    {text:'áfrica',category:'ubicación'},
    {text:'brasil',category:'ubicación'},
    {text:'canadá',category:'ubicación'},
    {text:'casino',category:'ubicación'},
    {text:'castillo',category:'ubicación'},
    {text:'iglesia',category:'ubicación'},
    {text:'circo',category:'ubicación'},
    {text:'dallas',category:'ubicación'},
    {text:'francia',category:'ubicación'},
    {text:'hawai',category:'ubicación'},
    {text:'bote de remos',category:'transporte'},
    {text:'lanzadera',category:'transporte'},
    {text:'avión',category:'transporte'},
    {text:'montacargas',category:'transporte'},
    {text:'carrito de golf',category:'transporte'},
    {text:'barco de vela',category:'transporte'},
    {text:'grúa',category:'transporte'},
    {text:'triciclo',category:'transporte'},
    {text:'zeppelin',category:'transporte'},
    {text:'bicicleta',category:'transporte'},
    {text:'trineo de perros',category:'transporte'},
    {text:'minivan',category:'transporte'},
    {text:'porsche',category:'transporte'},
    {text:'scooter',category:'transporte'},
    {text:'tractor',category:'transporte'},
    {text:'remolcador',category:'transporte'},
    {text:'gaita',category:'música'},
    {text:'guitarra',category:'música'},
    {text:'Daft Punk',category:'música'},
    {text:'macarena',category:'música'},
    {text:'caja de música',category:'música'},
    {text:'Skrillex',category:'música'},
    {text:'trombón',category:'música'},
    {text:'The Beatles',category:'música'},
    {text:'Beyoncé',category:'música'},
    {text:'Blondie',category:'música'},
    {text:'Bon Jovi',category:'música'},
    {text:'batería',category:'música'},
    {text:'dubstep',category:'música'},
    {text:'Nirvana',category:'música'},
    {text:'Outkast',category:'música'},
    {text:'Shakira',category:'música'},
    {text:'ukelele',category:'música'},
    {text:'grifo',category:'mitología'},
    {text:'Atlántida',category:'mitología'},
    {text:'Hércules',category:'mitología'},
    {text:'Minotauro',category:'mitología'},
    {text:'Poseidón',category:'mitología'},
    {text:'Bigfoot',category:'mitología'},
    {text:'centauro',category:'mitología'},
    {text:'cíclope',category:'mitología'},
    {text:'diosa',category:'mitología'},
    {text:'Júpiter',category:'mitología'},
    {text:'sirena',category:'mitología'},
    {text:'monstruo',category:'mitología'},
    {text:'Neptuno',category:'mitología'},
    {text:'Pegaso',category:'mitología'},
    {text:'Fénix',category:'mitología'},
    {text:'unicornio',category:'mitología'},
    {text:'vampiro',category:'mitología'},
    {text:'dragón',category:'mitología'},
    {text:'Angelina',category:'persona famosa'},
    {text:'Bob Dylan',category:'persona famosa'},
    {text:'Brad Pitt',category:'persona famosa'},
    {text:'Bruce Lee',category:'persona famosa'},
    {text:'Geronimo',category:'persona famosa'},
    {text:'Green Day',category:'persona famosa'},
    {text:'Kate Moss',category:'persona famosa'},
    {text:'Lady Gaga',category:'persona famosa'},
    {text:'Lil Wayne',category:'persona famosa'},
    {text:'Ludacris',category:'persona famosa'},
    {text:'MC Hammer',category:'persona famosa'},
    {text:'Tom Hanks',category:'persona famosa'},
    {text:'Beckham',category:'persona famosa'},
    {text:'Colbert',category:'persona famosa'},
    {text:'Jay Leno',category:'persona famosa'},
    {text:'Lincoln',category:'persona famosa'},
    {text:'Picasso',category:'persona famosa'},
    {text:'Rihanna',category:'persona famosa'},
    {text:'Van Gogh',category:'persona famosa'},
    {text:'Justin Bieber',category:'persona famosa'},
    {text:'Eminem',category:'persona famosa'},
    {text:'Gandhi',category:'persona famosa'},
    {text:'béisbol',category:'deportes'},
    {text:'mancuerna',category:'deportes'},
    {text:'fútbol',category:'deportes'},
    {text:'poste de gol',category:'deportes'},
    {text:'palos de golf',category:'deportes'},
    {text:'halfpipe',category:'deportes'},
    {text:'balonmano',category:'deportes'},
    {text:'patinaje sobre hielo',category:'deportes'},
    {text:'saltar la cuerda',category:'deportes'},
    {text:'salto largo',category:'deportes'},
    {text:'minigolf',category:'deportes'},
    {text:'Juegos Olímpicos',category:'deportes'},
    {text:'ping-pong',category:'deportes'},
    {text:'clavada',category:'deportes'},
    {text:'trineo',category:'deportes'},
    {text:'natación',category:'deportes'},
    {text:'tiro con arco',category:'deportes'},
    {text:'bolos',category:'deportes'},
    {text:'esgrima',category:'deportes'},
    {text:'pesca',category:'deportes'},
    {text:'frisbee',category:'deportes'},
    {text:'homerun',category:'deportes'},
    {text:'jabalina',category:'deportes'},
    {text:'rebote',category:'deportes'},
    {text:'árbitro',category:'deportes'},
    {text:'boxeo',category:'deportes'},
    {text:'Haymitch',category:'cultura popular'},
    {text:'Autobots',category:'cultura popular'},
    {text:'Los Vengadores',category:'cultura popular'},
    {text:'Catwoman',category:'cultura popular'},
    {text:'Garfield',category:'cultura popular'},
    {text:'Iron Chef',category:'cultura popular'},
    {text:'El Rey León',category:'cultura popular'},
    {text:'Splinter',category:'cultura popular'},
    {text:'Star Trek',category:'cultura popular'},
    {text:'Star Wars',category:'cultura popular'},
    {text:'Superman',category:'cultura popular'},
    {text:'Aladdín',category:'cultura popular'},
    {text:'Aquaman',category:'cultura popular'},
    {text:'Astérix',category:'cultura popular'},
    {text:'Ojo de Halcón',category:'cultura popular'},
    {text:'Katniss',category:'cultura popular'},
    {text:'Madonna',category:'cultura popular'},
    {text:'Metroid',category:'cultura popular'},
    {text:'Pikachu',category:'cultura popular'},
    {text:'El Acertijo',category:'cultura popular'},
    {text:'Rugrats',category:'cultura popular'},
    {text:'Dos Caras',category:'cultura popular'},
    {text:'Avatar',category:'cultura popular'},
    {text:'Barbie',category:'cultura popular'},
    {text:'Batman',category:'cultura popular'},
    {text:'Beavis',category:'cultura popular'},
    {text:'Bowser',category:'cultura popular'},
    {text:'asesino',category:'profesión'},
    {text:'director',category:'profesión'},
    {text:'gánster',category:'profesión'},
    {text:'jardinero',category:'profesión'},
    {text:'mago',category:'profesión'},
    {text:'princesa',category:'profesión'},
    {text:'camarera',category:'profesión'},
    {text:'luchador',category:'profesión'},
    {text:'carnicero',category:'profesión'},
    {text:'capitán',category:'profesión'},
    {text:'cajero',category:'profesión'},
    {text:'vaquera',category:'profesión'},
    {text:'dentista',category:'profesión'},
    {text:'baterista',category:'profesión'},
    {text:'gimnasta',category:'profesión'},
    {text:'cartero',category:'profesión'},
    {text:'lechero',category:'profesión'},
    {text:'pintor',category:'profesión'},
    {text:'fontanero',category:'profesión'},
    {text:'limpiador de piscinas',category:'profesión'},
    {text:'sheriff',category:'profesión'},
    {text:'soldado',category:'profesión'},
    {text:'cirujano',category:'profesión'},
    {text:'maestro',category:'profesión'},
    {text:'guerrero',category:'profesión'},
    {text:'artista',category:'profesión'},
    {text:'barbero',category:'profesión'},
    {text:'vaquero',category:'profesión'},
    {text:'médico',category:'profesión'},
    {text:'agricultor',category:'profesión'},
    {text:'dinosaurio',category:'animal'},
    {text:'elefante',category:'animal'},
    {text:'flamenco',category:'animal'},
    {text:'pez dorado',category:'animal'},
    {text:'canguro',category:'animal'},
    {text:'mosquito',category:'animal'},
    {text:'pingüinos',category:'animal'},
    {text:'reno',category:'animal'},
    {text:'escorpión',category:'animal'},
    {text:'caballito de mar',category:'animal'},
    {text:'ardilla',category:'animal'},
    {text:'estrella de mar',category:'animal'},
    {text:'tortuga',category:'animal'},
    {text:'colmena',category:'animal'},
    {text:'búfalo',category:'animal'},
    {text:'bagre',category:'animal'},
    {text:'pollo',category:'animal'},
    {text:'delfín',category:'animal'},
    {text:'pluma',category:'animal'},
    {text:'luciérnaga',category:'animal'},
    {text:'panda rojo',category:'animal'},
    {text:'jirafa',category:'animal'},
    {text:'gorila',category:'animal'},
    {text:'hámster',category:'animal'},
    {text:'mariquita',category:'animal'},
    {text:'lamprea',category:'animal'},
    {text:'leopardo',category:'animal'},
    {text:'langosta',category:'animal'},
    {text:'mamut',category:'animal'},
    {text:'narval',category:'animal'},
    {text:'pulpo',category:'animal'},
    {text:'avestruz',category:'animal'},
    {text:'pavo real',category:'animal'},
    {text:'pingüino',category:'animal'},
    {text:'pitbull',category:'animal'},
    {text:'mapache',category:'animal'},
    {text:'reptil',category:'animal'},
    {text:'gallo',category:'animal'},
    {text:'gaviota',category:'animal'},
    {text:'renacuajo',category:'animal'},
    {text:'plátano',category:'alimento'},
    {text:'burro',category:'animal'},
    {text:'baguette',category:'alimento'},
    {text:'barbacoa',category:'alimento'},
    {text:'brócoli',category:'alimento'},
    {text:'espresso',category:'alimento'},
    {text:'comida rápida',category:'alimento'},
    {text:'glaseado',category:'alimento'},
    {text:'salsa picante',category:'alimento'},
    {text:'comida basura',category:'alimento'},
    {text:'piruleta',category:'alimento'},
    {text:'macarrones',category:'alimento'},
    {text:'albóndiga',category:'alimento'},
    {text:'seta',category:'alimento'},
    {text:'tortitas',category:'alimento'},
    {text:'polo helado',category:'alimento'},
    {text:'sándwich',category:'alimento'},
    {text:'Skittles',category:'alimento'},
    {text:'cono helado',category:'alimento'},
    {text:'salsa de soja',category:'comida'},
    {text:'aguacate',category:'comida'},
    {text:'brownie',category:'comida'},
    {text:'burrito',category:'comida'},
    {text:'coco',category:'comida'},
    {text:'galletas',category:'comida'},
    {text:'perrito caliente de maíz',category:'comida'},
    {text:'magdalena',category:'comida'},
    {text:'doritos',category:'comida'},
    {text:'rollo de huevo',category:'comida'},
    {text:'hueso de jamón',category:'comida'},
    {text:'bocadillo de jamón',category:'comida'},
    {text:'ketchup',category:'comida'},
    {text:'mostaza',category:'comida'},
    {text:'fideos',category:'comida'},
    {text:'avena',category:'comida'},
    {text:'tortitas',category:'comida'},
    {text:'melocotones',category:'comida'},
    {text:'palomitas de maíz',category:'comida'},
    {text:'pretzel',category:'comida'},
    {text:'calabaza',category:'comida'},
    {text:'salchicha',category:'comida'},
    {text:'mariscos',category:'comida'},
    {text:'espinacas',category:'comida'},
    {text:'twinkie',category:'comida'},
    {text:'cereal',category:'comida'},
    {text:'queso',category:'comida'},
    {text:'café',category:'comida'},
    {text:'galleta',category:'comida'},
]